document.writeln("<!-- 侧边栏开始 -->");
document.writeln("	<div class=\'leftbar\'>");
document.writeln("		<div class=\'leftbar-cont\'>");
document.writeln("			<i class=\'icon icon-logo\' title=\'乐钢网加工管理系统\'></i>");
document.writeln("			<div class=\'scroll\' title=\'展开/隐藏\'>");
document.writeln("				<i class=\'icon icon-scroll\'></i>");
document.writeln("			</div>");
document.writeln("			<ul class=\'second-menu mt30\'>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list newpur ellipsis\' title=\'新增采购\' href=\'newpurch.html\'><i class=\'icons icons-smenu icons-smenu-newpur\'></i><span class=\'smenu-text\'>新增采购</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list purprice ellipsis\' title=\'采购核价\' href=\'purchaseprice.html\'><i class=\'icons icons-smenu icons-smenu-purprice\'></i><span class=\'smenu-text\'>采购核价</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list accessapp ellipsis\' title=\'辅料审批\' href=\'accessapproval.html\'><i class=\'icons icons-smenu icons-smenu-accessapp\'></i><span class=\'smenu-text\'>辅料审批</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list accessstr ellipsis\' title=\'辅料入库\' href=\'accessstorage.html\'><i class=\'icons icons-smenu icons-smenu-accessstr\'></i><span class=\'smenu-text\'>辅料入库</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list accessoutlib ellipsis\' title=\'辅料出库\' href=\'outlibrary.html\'><i class=\'icons icons-smenu icons-smenu-accessoutlib\'></i><span class=\'smenu-text\'>辅料出库</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list outlib ellipsis\' title=\'出库确认\' href=\'outlibapproval.html\'><i class=\'icons icons-smenu icons-smenu-outlib\'></i><span class=\'smenu-text\'>出库确认</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list paymentapl ellipsis\' title=\'辅料付款申请\' href=\'paymentapl.html\'><i class=\'icons icons-smenu icons-smenu-accesspaymt\'></i><span class=\'smenu-text\'>辅料付款申请</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list paymentexe ellipsis\' title=\'辅料付款执行\' href=\'paymentexe.html\'><i class=\'icons icons-smenu icons-smenu-accesspaymt\'></i><span class=\'smenu-text\'>辅料付款执行</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list  accessdetail ellipsis\' title=\'辅料盘点\' href=\'accessdetail.html\'><i class=\'icons icons-smenu icons icons-smenu-accesspaymt\'></i><span class=\'smenu-text\'>辅料盘点</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list custowned ellipsis\' title=\'客户自备辅料\' href=\'selfprdaccess.html\'><i class=\'icons icons-smenu icons-smenu-custowned\'></i><span class=\'smenu-text\'>客户自备辅料</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list accessConfirm ellipsis\' title=\'辅料领用确认\' href=\'accessConfirm.html\'><i class=\'icons icons-smenu icons-smenu-accesspaymt\'></i><span class=\'smenu-text\'>辅料领用确认</span></a>");
document.writeln("				</li>");
document.writeln("			</ul><!--second-menu -->");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<!-- 侧边栏结束 -->");