document.writeln("<!-- 侧边栏开始 -->");
document.writeln("	<div class=\'leftbar\'>");
document.writeln("		<div class=\'leftbar-cont\'>");
document.writeln("			<i class=\'icon icon-logo\' title=\'乐钢网加工管理系统\'></i>");
document.writeln("			<div class=\'scroll\' title=\'展开/隐藏\'>");
document.writeln("				<i class=\'icon icon-scroll\'></i>");
document.writeln("			</div>");
document.writeln("			<ul class=\'second-menu mt30\'>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list newstorage ellipsis\' title=\'新增入库\' href=\'customorders.html\'>");
document.writeln("						<i class=\'icons icons-smenu icons-smenu-newstr\'></i>");
document.writeln("						<span class=\'smenu-text\'>新增入库</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list releaselist ellipsis\' title=\'发布加工单\' href=\'releaseprosht.html\'>");
document.writeln("					<i class=\'icons icons-smenu icons-smenu-releasewo\'></i>");
document.writeln("					<span class=\'smenu-text\'>发布加工单</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list applyfordl ellipsis\' title=\'申请提货\' href=\'applyfdly.html\'>");
document.writeln("					<i class=\'icons icons-smenu icons-smenu-applyfd\'></i>");
document.writeln("					<span class=\'smenu-text\'>申请提货</span></a>");
document.writeln("				</li>");
document.writeln("			</ul><!--second-menu -->");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<!-- 侧边栏结束 -->");