document.writeln("<!-- 侧边栏开始 -->");
document.writeln("	<div class=\'leftbar\'>");
document.writeln("		<div class=\'leftbar-cont\'>");
document.writeln("			<i class=\'icon icon-logo\' title=\'乐钢网加工管理系统\'></i>");
document.writeln("			<div class=\'scroll\' title=\'展开/隐藏\'>");
document.writeln("				<i class=\'icon icon-scroll\'></i>");
document.writeln("			</div>");
document.writeln("			<ul class=\'second-menu mt30\'>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list receipt ellipsis\' title=\'收款\' href=\'receipt.html\'><i class=\'icons icons-smenu  icons-smenu-receipt\'></i><span class=\'smenu-text\'>收款</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list paymtreq ellipsis\' title=\'付款审批\' href=\'paymtreq.html\'><i class=\'icons icons-smenu icons-smenu-payt\'></i><span class=\'smenu-text\'>付款申请</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list paymtapproval ellipsis\' title=\'付款审批\' href=\'paymtapproval.html\'><i class=\'icons icons-smenu icons-smenu-payt\'></i><span class=\'smenu-text\'>付款审批</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list paymentlist ellipsis\' title=\'付款执行\' href=\'paymentlist.html\'><i class=\'icons icons-smenu icons-smenu-payt\'></i><span class=\'smenu-text\'>付款执行</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list invoicereg ellipsis\' title=\'发票登记\' href=\'invoicereg.html\'><i class=\'icons icons-smenu  icons-smenu-invoicergt\'></i><span class=\'smenu-text\'>发票登记</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list billingpage ellipsis\' title=\'开票\' href=\'billingpage.html\'><i class=\'icons icons-smenu  icons-smenu-invoicergt\'></i><span class=\'smenu-text\'>开票</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list receiveinvoice ellipsis\' title=\'收票\' href=\' receiveinvoice.html\'><i class=\'icons icons-smenu icons-smenu-tickets\'></i><span class=\'smenu-text\'>收票</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list waterelefeeapply ellipsis\' title=\'水电申请\' href=\'waterelefeeapply.html\'><i class=\'icons icons-smenu icons-smenu-payt\'></i><span class=\'smenu-text\'>水电申请</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list maintfeeapply ellipsis\' title=\'维修申请\' href=\' maintfeeapply.html\'><i class=\'icons icons-smenu icons-smenu-wemaint\'></i><span class=\'smenu-text\'>维修申请</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list maintapproval ellipsis\' title=\'水电维修审批\' href=\'maintapproval.html\'><i class=\'icons icons-smenu icons-smenu-wemaint\'></i><span class=\'smenu-text\'>水电维修审批</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list watmaintpay ellipsis\' title=\'水电维修付款\' href=\'watmaintpay.html\'><i class=\'icons icons-smenu icons-smenu-wemaint\'></i><span class=\'smenu-text\'>水电维修付款</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list rentFee ellipsis\' title=\'租赁收入\' href=\'rent1.html\'><i class=\'icons icons-smenu icons-smenu-divid\'></i><span class=\'smenu-text\'>租赁收入</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list divid ellipsis\' title=\'分红\' href=\'dividendpage.html\'><i class=\'icons icons-smenu icons-smenu-divid\'></i><span class=\'smenu-text\'>分红</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list commissionapply ellipsis\' title=\'佣金申请\' href=\'commissionapply.html\'><i class=\'icons icons-smenu icons-smenu-payt\'></i><span class=\'smenu-text\'>佣金申请</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list commission ellipsis\' title=\'佣金审核\' href=\'commission.html\'><i class=\'icons icons-smenu icons-smenu-commis\'></i><span class=\'smenu-text\'>佣金审核</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list afterSale ellipsis\' title=\'售后审批\' href=\'afterSale.html\'><i class=\'icons icons-smenu icons-smenu-commis\'></i><span class=\'smenu-text\'>售后审批</span></a>");
document.writeln("				</li>");
document.writeln("			</ul><!--second-menu -->");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<!-- 侧边栏结束 -->");