document.writeln("<!-- 侧边栏开始 -->");
document.writeln("	<div class=\'leftbar\'>");
document.writeln("		<div class=\'leftbar-cont\'>");
document.writeln("			<i class=\'icon icon-logo\' title=\'乐钢网加工管理系统\'></i>");
document.writeln("			<div class=\'scroll\' title=\'展开/隐藏\'>");
document.writeln("				<i class=\'icon icon-scroll\'></i>");
document.writeln("			</div>");
document.writeln("			<ul class=\'second-menu mt30\'>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list procpttable ellipsis\' title=\'加工订单表\' href=\'procpttable.html\'><i class=\'icons icons-smenu icons-smenu-procapt\'></i><span class=\'smenu-text\'>加工订单表</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list addunitpro ellipsis\' title=\'新增机组加工表\' href=\'addunitpro.html\'><i class=\'icons icons-smenu  icons-smenu-unitinfo\'></i><span class=\'smenu-text\'>新增机组加工表</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list machcapacity ellipsis\' title=\'加工能力\' href=\'machcapacity.html\'><i class=\'icons icons-smenu  icons-smenu-comrd\'></i><span class=\'smenu-text\'>加工能力</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list unitinformgt1 ellipsis\' title=\'机组管理\' href=\'jgbz.html\'><i class=\'icons icons-smenu  icons-smenu-maintrgt\'></i><span class=\'smenu-text\'>机组管理</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list unitinformgt ellipsis\' title=\'班组信息管理\' href=\'unitinformgt.html\'><i class=\'icons icons-smenu  icons-smenu-maintrgt\'></i><span class=\'smenu-text\'>班组信息管理</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list commgt ellipsis\' title=\'商品管理\' href=\'commgt.html\'><i class=\'icons icons-smenu  icons-smenu-maintrd\'></i><span class=\'smenu-text\'>商品管理</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list maintregist ellipsis\' title=\'维修登记\' href=\'maintregist.html\'><i class=\'icons icons-smenu  icons-smenu-maintrd\'></i><span class=\'smenu-text\'>维修登记</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list maintrecords ellipsis\' title=\'维修记录\' href=\'maintrecords.html\'><i class=\'icons icons-smenu  icons-smenu-maintrd\'></i><span class=\'smenu-text\'>维修记录</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list credit ellipsis\' title=\'授信管理\' href=\'credit.html\'><i class=\'icons icons-smenu  icons-smenu-maintrd\'></i><span class=\'smenu-text\'>授信管理</span></a>");
document.writeln("				</li>");
document.writeln("			</ul><!--second-menu -->");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<!-- 侧边栏结束 -->");