document.writeln("<!-- 侧边栏开始 -->");
document.writeln("	<div class=\'leftbar\'>");
document.writeln("		<div class=\'leftbar-cont\'>");
document.writeln("			<i class=\'icon icon-logo\' title=\'乐钢网加工管理系统\'></i>");
document.writeln("			<div class=\'scroll\' title=\'展开/隐藏\'>");
document.writeln("				<i class=\'icon icon-scroll\'></i>");
document.writeln("			</div>");
document.writeln("			<ul class=\'second-menu mt30\'>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list permset\' title=\'人员权限\' href=\'privilegemgt.html\'>");
document.writeln("						<i class=\'icons icons-smenu icons-smenu-permset\'></i>");
document.writeln("						<span class=\'smenu-text\'>人员权限</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list rolepri\' title=\'>角色权限\' href=\'roleperm.html\'>");
document.writeln("						<i class=\'icons icons-smenu icons-smenu-role\'></i>");
document.writeln("						<span class=\'smenu-text\'>角色权限</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list instoragecf newstaff\' title=\'新增人员\' href=\'newstaff.html\'>");
document.writeln("					<i class=\'icons icons-smenu icons-smenu-newstaff\'></i>");
document.writeln("					<span class=\'smenu-text\'>新增人员</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list actcenter\' title=\'账户中心\' href=\'accountcenter.html\'>");
document.writeln("					<i class=\'icons icons-smenu icons-smenu-accountcenter\'></i>");
document.writeln("					<span class=\'smenu-text\'>账户中心</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list prosheetd\' title=\'注册协议\' href=\'javascript:void(0);\'>");
document.writeln("					<i class=\'icons icons-smenu icons-smenu-registptl\'></i>");
document.writeln("					<span class=\'smenu-text\'>注册协议</span></a>");
document.writeln("				</li>");
document.writeln("			</ul><!--second-menu -->");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<!-- 侧边栏结束 -->");