document.writeln("<div class=\'leftbar\'>");
document.writeln("		<div class=\'leftbar-cont\'>");
document.writeln("			<i class=\'icon icon-logo\' title=\'乐钢网加工管理系统\'></i>");
document.writeln("			<div class=\'scroll\' title=\'展开/隐藏\'>");
document.writeln("				<i class=\'icon icon-scroll\'></i>");
document.writeln("			</div>");
document.writeln("			<ul class=\'second-menu mt30\'>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list ordertk ellipsis\' title=\'订单跟踪\' href=\'ordertracking.html\'><i class=\'icons icons-smenu icons-smenu-ordtr\'></i><span class=\'smenu-text\'>订单跟踪</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list instoragecf ellipsis\' title=\'入库确认\' href=\'storagelist.html\'><i class=\'icons icons-smenu icons-smenu-strtr\'></i><span class=\'smenu-text\'>入库确认</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list prosheetd ellipsis\' title=\'加工单审核\' href=\'billslist.html\'><i class=\'icons icons-smenu icons-smenu-proaudit\'></i><span class=\'smenu-text\'>加工单审核</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list schedul ellipsis\' title=\'生产排单表\' href=\'schedulinglist.html\'><i class=\'icons icons-smenu icons-smenu-prolist\'></i><span class=\'smenu-text\'>生产排单表</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list checkacpt ellipsis\' title=\'验收入库\' href=\'acceptlist.html\'><i class=\'icons icons-smenu icons-smenu-acceptstr\'></i><span class=\'smenu-text\'>验收入库</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list distribtpdt ellipsis\' title=\'码单出库\' href=\'outlist.html\'><i class=\'icons icons-smenu icons-smenu-codeoutlib\'></i><span class=\'smenu-text\'>码单出库</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list exitpermit ellipsis\' title=\'出门证\' href=\'cardslist.html\'><i class=\'icons icons-smenu icons-smenu-exittic\'></i><span class=\'smenu-text\'>出门证</span></a>");
document.writeln("				</li>");
document.writeln("			</ul><!--second-menu -->");
document.writeln("		</div>");
document.writeln("	</div>");