

document.writeln("<!-- 侧边栏开始 -->");
document.writeln("	<div class=\'leftbar\'>");
document.writeln("		<div class=\'leftbar-cont\'>");
document.writeln("			<i class=\'icon icon-logo\' title=\'乐钢网加工管理系统\'></i>");
document.writeln("			<div class=\'scroll\' title=\'展开/隐藏\'>");
document.writeln("				<i class=\'icon icon-scroll\'></i>");
document.writeln("			</div>");
document.writeln("			<ul class=\'second-menu mt30\'>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list orderreport ellipsis\' title=\'订单报表\' href=\'orderreport.html\'><i class=\'icons icons-smenu  icons-smenu-report\'></i><span class=\'smenu-text\'>订单报表</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list spotdetail ellipsis\' title=\'货物明细表\' href=\'spotdetail.html\'><i class=\'icons icons-smenu icons-smenu-cargolist\'></i><span class=\'smenu-text\'>货物明细表</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list inventst ellipsis\' title=\'盘点明细表\' href=\'inventst.html\'><i class=\'icons icons-smenu  icons-smenu-inventorylis\'></i><span class=\'smenu-text\'>盘点明细表</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list strdayrpt ellipsis\' title=\'订单报表\' href=\'strdayrpt.html\'><i class=\'icons icons-smenu  icons-smenu-report\'></i><span class=\'smenu-text\'>入库日报表</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list comfacmgt ellipsis\' title=\'提成系数管理\' href=\'comfacmgt.html\'><i class=\'icons icons-smenu  icons-smenu-comfscmgt\'></i><span class=\'smenu-text\'>提成系数管理</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list comfactrv ellipsis\' title=\'提成系数管理\' href=\'comfactrv.html\'><i class=\'icons icons-smenu  icons-smenu-comfscmgt\'></i><span class=\'smenu-text\'>提成系数审核</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list personbnft ellipsis\' title=\'人员效益表\' href=\'personbnft.html\'><i class=\'icons icons-smenu icons-smenu-personbf\'></i><span class=\'smenu-text\'>人员效益表</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list businessdata ellipsis\' title=\'业务数据分析\' href=\'businessdata.html\'><i class=\'icons icons-smenu  \'></i><span class=\'smenu-text\'>业务数据分析</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list customeroutput ellipsis\' title=\'客户产值分析\' href=\'customeroutput.html\'><i class=\'icons icons-smenu  \'></i><span class=\'smenu-text\'>客户产值分析</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list shourubnft ellipsis\' title=\'收入执行表\' href=\'srzxbnft.html\'><i class=\'icons icons-smenu icons-smenu-personbf  \'></i><span class=\'smenu-text\'>收入执行表</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list maolibnft ellipsis\' title=\'毛利统计表\' href=\'maolibnft.html\'><i class=\'icons icons-smenu icons-smenu-personbf  \'></i><span class=\'smenu-text\'>毛利统计表</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list managerbnft ellipsis\' title=\'管理员收益统计表\' href=\'manangerbnft.html\'><i class=\'icons icons-smenu icons-smenu-personbf  \'></i><span class=\'smenu-text\'>管理员收益统计表</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list flstock ellipsis\' title=\'辅料库存\' href=\'fliaokc.html\'><i class=\'icons icons-smenu icons-smenu-personbf  \'></i><span class=\'smenu-text\'>辅料库存</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list flpandian ellipsis\' title=\'辅料盘点\' href=\'flpandian.html\'><i class=\'icons icons-smenu icons-smenu-personbf  \'></i><span class=\'smenu-text\'>辅料盘点</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list flrkpd ellipsis\' title=\'辅料入库日报表\' href=\'flrkreport.html\'><i class=\'icons icons-smenu icons-smenu-personbf  \'></i><span class=\'smenu-text\'>辅料入库日报表</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list flrkck ellipsis\' title=\'辅料出库日报表\' href=\'flckreport.html\'><i class=\'icons icons-smenu icons-smenu-personbf  \'></i><span class=\'smenu-text\'>辅料出库日报表</span>");
document.writeln("					</a>");
document.writeln("				</li>");
/*document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list sktjbb ellipsis\' title=\'收款统计表\' href=\'skreport.html\'><i class=\'icons icons-smenu icons-smenu-personbf  \'></i><span class=\'smenu-text\'>收款统计表</span>");
document.writeln("					</a>");
document.writeln("				</li>");*/
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list fktjbb ellipsis\' title=\'付款统计表\' href=\'fkreport.html\'><i class=\'icons icons-smenu icons-smenu-personbf  \'></i><span class=\'smenu-text\'>付款统计表</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list khfxb ellipsis\' title=\'成本分析\' href=\'customerreport.html\'><i class=\'icons icons-smenu icons-smenu-personbf  \'></i><span class=\'smenu-text\'>成本分析</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list khffxb ellipsis\' title=\'客户分析\' href=\'customerlistreport.html\'><i class=\'icons icons-smenu icons-smenu-personbf  \'></i><span class=\'smenu-text\'>客户分析</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list jybb ellipsis\' title=\'经营报表\' href=\'jyreport.html\'><i class=\'icons icons-smenu icons-smenu-personbf  \'></i><span class=\'smenu-text\'>经营报表</span>"); 
document.writeln("					</a>");
document.writeln("				</li>");



document.writeln("			</ul><!--second-menu -->");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<!-- 侧边栏结束 -->");