document.writeln("<!-- 头部导航栏开始 -->");
document.writeln("	<div class=\'topbar\'>");
document.writeln("		<div class=\'topline\'>");
document.writeln("			<a class=\'topline-span\'>");
document.writeln("				<i class=\'icon icon-commenu icon-user\'></i>");
document.writeln("				王家伟");
document.writeln("			</a>");
document.writeln("			<a class=\'topline-span\' onclick=\'\'>");
document.writeln("				<i class=\'icon icon-commenu icon-exit\'></i>");
document.writeln("				退出");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("");
document.writeln("		<div class=\'level-menu\'>");
document.writeln("			");
document.writeln("			<ul class=\'menu clearfix\'>");
document.writeln("			<li>");
document.writeln("				<a class=\'menu-list customorders\' href=\'../customorders/customorders.html\'><i class=\'icon icon-commenu icon-menu-cutord\'></i><span>定制下单</span></a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a class=\'menu-list promgttop\' href=\'../processingmgt/ordertracking.html\'><i class=\'icon icon-commenu icon-menu-promgt\'></i><span>加工管理</span></a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a class=\'menu-list finlmgttop\' href=\'../financialmgt/receipt.html\'><i class=\'icon icon-commenu icon-menu-finlmgt\'></i><span>财务管理</span></a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a class=\'menu-list accmgttop\' href=\'../accessmgt/newpurch.html\'><i class=\'icon icon-commenu icon-menu-accmgt\'></i><span>辅料管理</span></a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a class=\'menu-list wastemgttop\' href=\'../wastemgt/applicationforwt.html\'><i class=\'icon icon-commenu icon-menu-wastemgt\'></i><span>废料管理</span></a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a class=\'menu-list rptmgttop\' href=\'../reportmgt/orderreport.html\'><i class=\'icon icon-commenu icon-menu-rptmgt\'></i><span>报表管理</span></a>");
document.writeln("			</li>");
document.writeln("			");
document.writeln("			<li>");
document.writeln("				<a class=\'menu-list infomattop\' href=\'../infomat/procpttable.html\'><i class=\'icon icon-commenu icon-menu-infomat\'></i><span>信息维护</span></a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a class=\'menu-list basicinfotop\' href=\'../authoritymgt/privilegemgt.html\'><i class=\'icon icon-commenu icon-menu-basicinfo\'></i><span>基本信息</span></a>");
document.writeln("			</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<!-- 头部导航栏结束 -->");