document.writeln("<div class=\'leftbar\'>");
document.writeln("		<div class=\'leftbar-cont\'>");
document.writeln("			<i class=\'icon icon-logo\' title=\'乐钢网加工管理系统\'></i>");
document.writeln("			<div class=\'scroll\' title=\'展开/隐藏\'>");
document.writeln("				<i class=\'icon icon-scroll\'></i>");
document.writeln("			</div>");
document.writeln("			<ul class=\'second-menu mt30\'>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list applicationforwt ellipsis\' title=\'废料招标书申请\' href=\'applicationforwt.html\'><i class=\'icons icons-smenu  icons-smenu-book\'></i><span class=\'smenu-text\'>废料招标书申请</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list approvalofwt ellipsis\' title=\'废料招标书审批\' href=\'approvalofwt.html\'><i class=\'icons icons-smenu  icons-smenu-outlib\'></i><span class=\'smenu-text\'>废料招标书审批</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list wasteoutofstr ellipsis\' title=\'废料出入库\' href=\'wasteoutofstr.html\'><i class=\'icons icons-smenu icons-smenu-approval\'></i><span class=\'smenu-text\'>废料出入库</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list wastestockdt ellipsis\' title=\'废料库存明细\' href=\'wastestockdt.html\'><i class=\'icons icons-smenu  icons-smenu-stockdet\'></i><span class=\'smenu-text\'>废料库存明细</span></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class=\'smenu-list wasteindetail ellipsis\' title=\'废料收入明细\' href=\'wasteindetail.html\'><i class=\'icons icons-smenu icons-smenu-indet\'></i><span class=\'smenu-text\'>废料收入明细</span></a>");
document.writeln("				</li>");
document.writeln("			</ul><!--second-menu -->");
document.writeln("		</div>");
document.writeln("	</div>");